defaults:
  - _self_
  - dataset: beauty

# NOTE: you must set these (or override via CLI)
project_name: ""
checkpoint_dir: ""

seed: 42

use_pretrained_item_embeddings: True

# IMPORTANT: enable trainable delta (paper "ours" uses trainable delta)
train_delta: true

# Same delta constraint as paper baseline
max_delta_norm: 0.5

model:
  num_items: ${dataset.num_items}
  embedding_dim: ${dataset.embedding_dim}
  num_blocks: 2
  num_heads: 1
  p: 0.3
  max_length: ${dataset.max_length}

recommender:
  learning_rate: 1e-3
  remove_seen: True
  metrics: ['NDCG', 'Recall']
  topk: 10

early_stopping:
  monitor: recommender-val-NDCG@10
  patience: 5
  mode: max

model_checkpoint:
  monitor: ${early_stopping.monitor}
  mode: ${early_stopping.mode}

trainer:
  devices: [0]
  max_epochs: 100
  val_check_interval: 1.0
  # optional if you want GPU/AMP:
  # accelerator: gpu
  # precision: 16-mixed

# NEW: cold delta initialization via warm KNN transfer (improves cold vs zero delta)
cold_knn:
  enabled: true
  k: 50
  temperature: 0.07
  alpha: 1.0
  batch_size: 2048

  # NEW: safety gate for cold-delta init (hybrid)
  gate:
    enabled: true

    # supported: maxsim_sigmoid | entropy_sigmoid
    type: maxsim_sigmoid

    # sigmoid(max_sim - tau) with sharpness=beta
    tau: 0.25
    beta: 20.0

    # clamp gate to [g_min, g_max]
    g_min: 0.0
    g_max: 1.0

    # if max_sim < hard_min_sim => gate = 0 (hard safety)
    hard_min_sim: 0.05
